version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
    volumes:
      - .:/app
    command: flask run

networks:
  default:
    name: honeypot-network

volumes:
  app-data:
