AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to deploy honeypot application on Amazon ECS'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the ECS cluster will be created

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first public subnet ID for the ALB

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second public subnet ID for the ALB

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first private subnet ID for the ECS tasks

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second private subnet ID for the ECS tasks

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: honeypot-cluster

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: frontend-honeypot
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: frontend-honeypot
          Image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node:2.0
          PortMappings:
            - ContainerPort: 9000
          Environment:
            - Name: BASE_URL
              Value: !Sub "http://${ProdCatalogService.DNSName}:5000/products/"
            - Name: AWS_XRAY_DAEMON_ADDRESS
              Value: xray-service.default:2000
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:9000/ping || exit 1
            Interval: 10
            Timeout: 5
            Retries: 3

  ProdCatalogTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: prodcatalog-honeypot
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: prodcatalog-honeypot
          Image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/product_catalog:1.0
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: AGG_APP_URL
              Value: !Sub "http://${ProdDetailService.DNSName}:3000/catalogDetail"
            - Name: AWS_XRAY_DAEMON_ADDRESS
              Value: xray-service.default:2000
            - Name: DATABASE_SERVICE_URL
              Value: mysql.workshop
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:5000/products/ping || exit 1
            Interval: 10
            Timeout: 5
            Retries: 3

  ProdDetailTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: proddetail-honeypot
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: proddetail-honeypot
          Image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/catalog_detail:2.0
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: AWS_XRAY_DAEMON_ADDRESS
              Value: xray-service.default:2000
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/ping || exit 1
            Interval: 10
            Timeout: 5
            Retries: 3

  FrontendService:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      ServiceName: frontend-honeypot
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref FrontendTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: frontend-honeypot
          ContainerPort: 9000
          TargetGroupArn: !Ref ALBTargetGroup

  ProdCatalogService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: prodcatalog-honeypot
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ProdCatalogTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          SecurityGroups:
            - !Ref ECSSecurityGroup

  ProdDetailService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: proddetail-honeypot
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ProdDetailTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          SecurityGroups:
            - !Ref ECSSecurityGroup

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /ping
      Name: honeypot-tg
      Port: 9000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  ALBDNSName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ALB.DNSName
