AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS deployment for the workshop application'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the existing VPC
  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the first public subnet
  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the second public subnet

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: WorkshopCluster

  # ECS Task Definitions
  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: frontend
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: frontend
          Image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node:2.0
          PortMappings:
            - ContainerPort: 9000
          Environment:
            - Name: BASE_URL
              Value: !Sub "http://${ALB.DNSName}:5000/products/"
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:9000/ping || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 0

  ProdCatalogTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: prodcatalog
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: prodcatalog
          Image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/product_catalog:1.0
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: AGG_APP_URL
              Value: !Sub "http://${ALB.DNSName}:3000/catalogDetail"
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:5000/products/ping || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 0

  ProdDetailTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: proddetail
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: proddetail
          Image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/catalog_detail:1.0
          PortMappings:
            - ContainerPort: 3000
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/ping || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 0

  # ECS Services
  FrontendService:
    Type: AWS::ECS::Service
    DependsOn: 
      - ALBListener
      - ProdCatalogService
    Properties:
      ServiceName: frontend-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref FrontendTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1Id
            - !Ref PublicSubnet2Id
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 9000
          TargetGroupArn: !Ref ALBTargetGroup

  ProdCatalogService:
    Type: AWS::ECS::Service
    DependsOn: 
      - ALBListener
      - ProdDetailService
    Properties:
      ServiceName: prodcatalog-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ProdCatalogTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1Id
            - !Ref PublicSubnet2Id
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: prodcatalog
          ContainerPort: 5000
          TargetGroupArn: !Ref ProdCatalogALBTargetGroup

  ProdDetailService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: proddetail-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ProdDetailTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1Id
            - !Ref PublicSubnet2Id
          SecurityGroups:
            - !Ref ECSSecurityGroup

  # Application Load Balancer
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroup

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /ping
      Name: ALBTargetGroup
      Port: 9000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  # Security Groups
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # Add a new ALB Listener Rule for the Product Catalog service
  ProdCatalogListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values: 
            - /products/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ProdCatalogALBTargetGroup

  # Add a new Target Group for the Product Catalog service
  ProdCatalogALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /products/ping
      Name: ProdCatalogALBTargetGroup
      Port: 5000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

Outputs:
  ALBDNSName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ALB.DNSName
  
  FrontendServiceURL:
    Description: URL for the Frontend Service
    Value: !Sub "http://${ALB.DNSName}"

  ECSClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref ECSCluster

  VPCId:
    Description: ID of the VPC
    Value: !Ref VpcId
